# ─────────────────────────────────────────────────────────────────
# Local Development Dockerfiles
# ─────────────────────────────────────────────────────────────────
FROM eclipse-temurin:25-jre-alpine

# Create non-root user for better security
RUN addgroup -S appgroup && \
    adduser  -S appuser -G appgroup

# Set working directory and copy application JAR
ENV APP_HOME=/app

WORKDIR $APP_HOME

# Copy from builder stage
COPY --chown=appuser:appgroup target/*.jar app.jar

RUN chmod 400 app.jar

USER appuser

EXPOSE 8001

ENTRYPOINT ["sh", "-c", "exec java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE} -jar app.jar"]
